### ISSUE TITLE
TypeError when trying to connect to open tab

### ISSUE THREAD

**Issue by Haubach** [Microsoft/edge-diagnostics-adapter#70]
I'm trying to get Edge-diagnostics-adapter up and running on the latest Insider build of Windows 10.

I am able to get the list of open tabs up, but once I click on any of them, the node task exits with a typeError.

```
$ node -v
v6.12.3


$ node out/src/edgeAdapter.js --port=9222 --servetools
Edge Diagnostics Adapter listening on port 9222...
Log: Injecting 'browser:assert.js'
Log: Injecting 'browser:common.js'
Log: Injecting 'browser:browser.js'
Log: Injecting 'browser:dom.js'
Log: Injecting 'browser:runtime.js'
Log: Injecting 'browser:page.js'
Log: Injecting 'browser:CssParser.js'
Log: Injecting 'browser:browserTool.js'
Log: Injecting 'browser:network.js'
Log: Injecting 'debugger:assert.js'
Log: Injecting 'debugger:common.js'
Log: Injecting 'debugger:debugger.js'
Log: Could not open NetworkProxy at path: C:\Users\Jacob\AppData\Roaming\npm\node_modules\edge-diagnostics-adapter\out\src\adapterService\..\..\lib\NetworkProxy.exe
C:\Users\Jacob\AppData\Roaming\npm\node_modules\edge-diagnostics-adapter\out\src\adapterService\edgeAdapterService.js:190
                        edgeAdapter.forwardTo(networkInstanceId, msg.toString());
                                    ^

TypeError: Incorrect arguments - forwardTo(instanceId: string, message: string): void
    at TypeError (native)
    at WebSocket.<anonymous> (C:\Users\Jacob\AppData\Roaming\npm\node_modules\edge-diagnostics-adapter\out\src\adapterService\edgeAdapterService.js:190:37)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at Receiver._receiver.onmessage (C:\Users\Jacob\AppData\Roaming\npm\node_modules\edge-diagnostics-adapter\node_modules\ws\lib\WebSocket.js:143:47)
    at Receiver.dataMessage (C:\Users\Jacob\AppData\Roaming\npm\node_modules\edge-diagnostics-adapter\node_modules\ws\lib\Receiver.js:389:14)
    at Receiver.getData (C:\Users\Jacob\AppData\Roaming\npm\node_modules\edge-diagnostics-adapter\node_modules\ws\lib\Receiver.js:330:12)
    at Receiver.startLoop (C:\Users\Jacob\AppData\Roaming\npm\node_modules\edge-diagnostics-adapter\node_modules\ws\lib\Receiver.js:165:16)
    at Receiver.add (C:\Users\Jacob\AppData\Roaming\npm\node_modules\edge-diagnostics-adapter\node_modules\ws\lib\Receiver.js:139:10)
    at Socket._ultron.on (C:\Users\Jacob\AppData\Roaming\npm\node_modules\edge-diagnostics-adapter\node_modules\ws\lib\WebSocket.js:139:22)`
```

**Comment by kingio** [comment]
This is a microsoft product, do not expect it to work properlly without having to make fixes.
Open `C:\Users\Jacob\AppData\Roaming\npm\node_modules\edge-diagnostics-adapter\out\src\adapterService\edgeAdapterService.js` with your favorite IDE and edit the following lines:
```js
if (_this.isMessageForNetworkProxy(msg)) {
                        edgeAdapter.forwardTo(networkInstanceId, msg.toString());
                    }
                    else {
                        edgeAdapter.forwardTo(instanceId, msg.toString());
                    }
```

to

```js
if (_this.isMessageForNetworkProxy(msg)) {
                        edgeAdapter.forwardTo(networkInstanceId.toString(), msg.toString());
                    }
                    else {
                        edgeAdapter.forwardTo(instanceId.toString(), msg.toString());
                    }
```
